apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.preempt_k8s.general.name }}
  namespace: {{ .Values.preempt_k8s.general.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.preempt_k8s.general.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.preempt_k8s.general.name }}
    namespace: {{ .Values.preempt_k8s.general.namespace }}
