apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.preempt_k8s.general.name }}
rules:
  - apiGroups: ["rtgroup.critical.com"]
    resources: ["rtresources", "rtresources/status"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
