apiVersion: v1
kind: ConfigMap
metadata:
  name: preempt-k8s
  namespace: realtime
  labels:
    app: preempt-k8s
data:
  MIN_WATCHDOGS: "10"
  MAX_WATCHDOGS: "20"
  THRESHOLD: "3"
  EVENT_QUEUE: "/eventqueue"
